CREATE TABLE [dbo].[RawStateVoterImport]
(	[UN] [nvarchar](max) NULL,
	[PARTY] [nvarchar](max) NULL,
	[D/P] [nvarchar](max) NULL,
	[LAST NAME] [nvarchar](max) NULL,
	[FIRST NAME] [nvarchar](max) NULL,
	[MIDDLE NAME] [nvarchar](max) NULL,
	[SUFFIX NAME] [nvarchar](max) NULL,
	[ASCENSION #] [nvarchar](max) NULL,
	[REG DATE] [nvarchar](max) NULL,
	[ORG REG DATE] [nvarchar](max) NULL,
	[DIST DATE] [nvarchar](max) NULL,
	[RESIDENCE ADDRESS] [nvarchar](max) NULL,
	[RESIDENCE CITY] [nvarchar](max) NULL,
	[RESIDENCE ZIP] [nvarchar](max) NULL,
	[MAILING ADDRESS1] [nvarchar](max) NULL,
	[MAILING ADDRESS2] [nvarchar](max) NULL,
	[MAILING ADDRESS3] [nvarchar](max) NULL,
	[MAILING CITY] [nvarchar](max) NULL,
	[MAILING STATE] [nvarchar](max) NULL,
	[MAILING ZIP] [nvarchar](max) NULL,
	[MAILING COUNTRY] [nvarchar](max) NULL,
	[GENDER] [nvarchar](max) NULL,
	[VH1] [nvarchar](max) NULL,
	[VH2] [nvarchar](max) NULL,
	[VH3] [nvarchar](max) NULL,
	[VH4] [nvarchar](max) NULL,
	[VH5] [nvarchar](max) NULL,
	[VH6] [nvarchar](max) NULL,
	[VH7] [nvarchar](max) NULL,
	[VH8] [nvarchar](max) NULL,
	[VH9] [nvarchar](max) NULL,
	[VH10] [nvarchar](max) NULL,
	[VH11] [nvarchar](max) NULL,
	[VH12] [nvarchar](max) NULL,
	[VH13] [nvarchar](max) NULL,
	[VH14] [nvarchar](max) NULL,
	[VH15] [nvarchar](max) NULL,
	[VH16] [nvarchar](max) NULL
)
