CREATE TABLE [dbo].[RawStateVoterImport]
(	[UN]                [CHAR](1) NULL,
	[PARTY]             [char](1) NULL,
	[D/P]               [CHAR](6) NULL,
	[LAST NAME]         [VARCHAR](50) NULL,
	[FIRST NAME]        [VARCHAR](50) NULL,
	[MIDDLE NAME]       [VARCHAR](50) NULL,
	[SUFFIX NAME]       [VARCHAR](10) NULL,
	[ASCENSION #]       INT NULL,
	[REG DATE]          [DATE] NULL,
	[ORG REG DATE]      [DATE] NULL,
	[DIST DATE]         [DATE] NULL,
	[RESIDENCE ADDRESS] [varchar](100) NULL,
	[RESIDENCE CITY]    [VARCHAR](100) NULL,
	[RESIDENCE ZIP]     [VARCHAR](100) NULL,
	[MAILING ADDRESS1]  [varchar](100) NULL,
	[MAILING ADDRESS2]  [varchar](100) NULL,
	[MAILING ADDRESS3]  [varchar](100) NULL,
	[MAILING CITY]      [VARCHAR](100) NULL,
	[MAILING STATE]     [VARCHAR](100) NULL,
	[MAILING ZIP]       [VARCHAR](10) NULL,
	[MAILING COUNTRY]   [VARCHAR](200) NULL,
	[GENDER]            [CHAR](1) NULL,
	[VH1]               [varchar](10) NULL,
	[VH2]               [varchar](10) NULL,
	[VH3]               [varchar](10) NULL,
	[VH4]               [varchar](10) NULL,
	[VH5]               [varchar](10) NULL,
	[VH6]               [varchar](10) NULL,
	[VH7]               [varchar](10) NULL,
	[VH8]               [varchar](10) NULL,
	[VH9]               [varchar](10) NULL,
	[VH10]              [varchar](10) NULL,
	[VH11]              [varchar](10) NULL,
	[VH12]              [varchar](10) NULL,
	[VH13]              [varchar](10) NULL,
	[VH14]              [varchar](10) NULL,
	[VH15]              [varchar](10) NULL,
	[VH16]              [varchar](10) NULL
)
