CREATE TABLE [dbo].[Voter]
(
	[VoterId]       INT NOT NULL PRIMARY KEY CLUSTERED ,
    [UN]            [CHAR](1) NULL,
	[Party]         [CHAR](1) NULL,
    [District]      INT NULL,
    [Precinct]      [CHAR](6), 
	[LastName]      [VARCHAR](50) NULL,
	[FirstName]     [VARCHAR](50) NULL,
	[MiddleName]    [VARCHAR](50) NULL,
	[Suffix]        [VARCHAR](10) NULL,
	[RegDate]       [Date] NULL,
	[OrgRegDate]    [Date] NULL,
	[DistDate]      [Date] NULL,
    [IsPrivate]     [BIT]  NULL, 
	[Address]       [VARCHAR](100) NULL,
	[City]          [VARCHAR](100) NULL,
	[Zip]           [VARCHAR](10) NULL,
	[MailingAddr1]  [VARCHAR](100) NULL,
	[MailingADdr2]  [VARCHAR](100) NULL,
	[MailingAddr3]  [VARCHAR](100) NULL,
	[MailingCity]   [VARCHAR](100) NULL,
	[MailingState]  [VARCHAR](100) NULL,
	[MailingZip]    [VARCHAR](10) NULL,
	[MailingCountry][varchar](200) NULL,
	[Gender]        [CHAR]   (1) NULL,
    [ValidFrom]     DATETIME2 (2) GENERATED ALWAYS AS ROW START,  
    [ValidTo]       DATETIME2 (2) GENERATED ALWAYS AS ROW END,  
    PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo)
) 
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.Voter_Temporal)); 
